### ISSUE TITLE
setup.py

### ISSUE THREAD

**Issue by FranklinYu** [alex/x509-validator#25]
In future, is this supposed to be part of the “cryptography” package, or would it become a stand-alone package? If the latter, shall we add a `setup.py`?

**Comment by alex** [comment]
We haven't finalized what the plan is for the future of this code.

**Comment by FranklinYu** [comment]
I came up with a quick and simple `setup.py` at https://github.com/FranklinYu/x509-validator/tree/packaging. Please tell me when it gets useful. Thanks for the efforts so far!
